In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
dataset=pd.read_csv('BRCA.csv')

In [4]:
dataset

,Patient_ID,Age,Gender,Protein1,Protein2,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36,FEMALE,0.080353,0.42638,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43,FEMALE,-0.420320,0.57807,26-Apr-17,9-Nov-18,Dead
2,TCGA-A8-A079,69,FEMALE,0.213980,1.31140,8-Sep-17,9-Jun-18,Alive
3,TCGA-D8-A1XR,56,FEMALE,0.345090,-0.21147,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56,FEMALE,0.221550,1.90680,6-May-17,27-Jun-19,Dead
...,...,...,...,...,...,...,...,...
329,TCGA-AN-A04A,36,FEMALE,0.231800,0.61804,11-Nov-19,9-Feb-20,Dead
330,TCGA-A8-A085,44,MALE,0.732720,1.11170,1-Nov-19,4-Mar-20,Dead
331,TCGA-A1-A0SG,61,FEMALE,-0.719470,2.54850,11-Nov-19,18-Jan-21,Dead
332,TCGA-A2-A0EU,79,FEMALE,0.479400,2.05590,21-Nov-19,19-Feb-21,Dead
333,TCGA-B6-A40B,76,FEMALE,-0.244270,0.92556,11-Nov-19,5-Jan-21,Dead